from PyQt5 import QtCore, QtGui, QtWidgets
import os
import connection
import mysql.connector
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator

mydb = connection.mydb

class Ui_MainWindowwww(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.F_Name = QtWidgets.QLabel(self.centralwidget)
        self.F_Name.setGeometry(QtCore.QRect(70, 50, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.F_Name.setFont(font)
        self.F_Name.setObjectName("F_Name")
        self.Name_2 = QtWidgets.QLabel(self.centralwidget)
        self.Name_2.setGeometry(QtCore.QRect(70, 120, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Name_2.setFont(font)
        self.Name_2.setText("")
        self.Name_2.setObjectName("Name_2")
        self.M_Name = QtWidgets.QLabel(self.centralwidget)
        self.M_Name.setGeometry(QtCore.QRect(70, 90, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.M_Name.setFont(font)
        self.M_Name.setObjectName("M_Name")
        self.L_Name = QtWidgets.QLabel(self.centralwidget)
        self.L_Name.setGeometry(QtCore.QRect(70, 130, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.L_Name.setFont(font)
        self.L_Name.setObjectName("L_Name")
        self.UID = QtWidgets.QLabel(self.centralwidget)
        self.UID.setGeometry(QtCore.QRect(70, 180, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UID.setFont(font)
        self.UID.setObjectName("UID")
        self.Mobile_number_1 = QtWidgets.QLabel(self.centralwidget)
        self.Mobile_number_1.setGeometry(QtCore.QRect(70, 230, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Mobile_number_1.setFont(font)
        self.Mobile_number_1.setObjectName("Mobile_number_1")
        self.Mobile_number_2 = QtWidgets.QLabel(self.centralwidget)
        self.Mobile_number_2.setGeometry(QtCore.QRect(70, 280, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Mobile_number_2.setFont(font)
        self.Mobile_number_2.setObjectName("Mobile_number_2")
        self.Aadhar_Number = QtWidgets.QLabel(self.centralwidget)
        self.Aadhar_Number.setGeometry(QtCore.QRect(70, 330, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Aadhar_Number.setFont(font)
        self.Aadhar_Number.setObjectName("Aadhar_Number")
        self.PAN_Number = QtWidgets.QLabel(self.centralwidget)
        self.PAN_Number.setGeometry(QtCore.QRect(70, 380, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PAN_Number.setFont(font)
        self.PAN_Number.setObjectName("PAN_Number")
        self.Date_Of_Birth = QtWidgets.QLabel(self.centralwidget)
        self.Date_Of_Birth.setGeometry(QtCore.QRect(70, 430, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Date_Of_Birth.setFont(font)
        self.Date_Of_Birth.setObjectName("Date_Of_Birth")
        self.Bloodgroup = QtWidgets.QLabel(self.centralwidget)
        self.Bloodgroup.setGeometry(QtCore.QRect(70, 480, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Bloodgroup.setFont(font)
        self.Bloodgroup.setObjectName("Bloodgroup")
        self.Sex = QtWidgets.QLabel(self.centralwidget)
        self.Sex.setGeometry(QtCore.QRect(70, 530, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Sex.setFont(font)
        self.Sex.setObjectName("Sex")
        self.Address = QtWidgets.QLabel(self.centralwidget)
        self.Address.setGeometry(QtCore.QRect(70, 580, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Address.setFont(font)
        self.Address.setObjectName("Address")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(750, 40, 211, 91))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Treating_Doctor = QtWidgets.QLabel(self.centralwidget)
        self.Treating_Doctor.setGeometry(QtCore.QRect(590, 190, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Treating_Doctor.setFont(font)
        self.Treating_Doctor.setObjectName("Treating_Doctor")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMRsys"))
        self.F_Name.setText(_translate("MainWindow", "First name:"))
        self.M_Name.setText(_translate("MainWindow", "Middle Name:"))
        self.L_Name.setText(_translate("MainWindow", "Last Name:"))
        self.UID.setText(_translate("MainWindow", "UID"))
        self.Mobile_number_1.setText(_translate("MainWindow", "Mobile Number 1:"))
        self.Mobile_number_2.setText(_translate("MainWindow", "Mobile Number 2:"))
        self.Aadhar_Number.setText(_translate("MainWindow", "Aadhar Number:"))
        self.PAN_Number.setText(_translate("MainWindow", "PAN Number:"))
        self.Date_Of_Birth.setText(_translate("MainWindow", "Date Of Birth:"))
        self.Bloodgroup.setText(_translate("MainWindow", "Bloodgroup:"))
        self.Sex.setText(_translate("MainWindow", "Sex:"))
        self.Address.setText(_translate("MainWindow", "Address:"))
        self.label.setText(_translate("MainWindow", "EMRsys"))
        self.Treating_Doctor.setText(_translate("MainWindow", "Treating Doctor:"))

    def retranslateuii(self,uid):
        ptiddet = connection.show_patient_details(uid)
        self.F_Name.setText("First name:" + ptiddet[0][1])
        self.M_Name.setText( "Middle Name:" + ptiddet[0][2])
        self.L_Name.setText("Last Name:" + ptiddet[0][3])
        self.UID.setText("UID:" + str(ptiddet[0][0]))
        self.Mobile_number_1.setText("Mobile Number 1:" + str(ptiddet[0][8]))
        self.Mobile_number_2.setText("Mobile Number 2:" + str(ptiddet[0][9]))
        self.Aadhar_Number.setText("Aadhar Number:" + str(ptiddet[0][10]))
        self.PAN_Number.setText("PAN Number:" + str(ptiddet[0][11]))
        self.Date_Of_Birth.setText("Date Of Birth:" + str(ptiddet[0][4]))
        self.Bloodgroup.setText("Bloodgroup:"+ str(ptiddet[0][7]))
        self.Sex.setText("Sex:"+ str(ptiddet[0][6]))
        self.Address.setText("Address:"+ str(ptiddet[0][12]))
        self.Treating_Doctor.setText("Treating Doctor:"+ str(ptiddet[0][13]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
