from PyQt5 import QtCore, QtGui, QtWidgets
import os
import connection
import mysql.connector
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
import Bill_pdfer

class Ui_MainWindowww(object):
    def setupUi(self, MainWindow,pt_UID,totalamount,name,Tx_ID):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(765, 722)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        validator = QRegExpValidator(QRegExp(r'[0-9]+'))
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 40, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 180, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 70, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 120, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 330, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 410, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Paid_Amount = QtWidgets.QLineEdit(self.centralwidget)
        self.Paid_Amount.setGeometry(QtCore.QRect(200, 410, 171, 41))
        self.Paid_Amount.setObjectName("Paid_Amount")
        self.Paid_Amount.setValidator(validator)
        self.Paid_Amount.setFont(font)
        self.Status = QtWidgets.QLineEdit(self.centralwidget)
        self.Status.setGeometry(QtCore.QRect(150, 550, 241, 61))
        self.Status.setObjectName("Status")
        self.Status.setFont(font)
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(70, 560, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.Proceed = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.feed_the_data(pt_UID,totalamount,Tx_ID))
        self.Proceed.setGeometry(QtCore.QRect(530, 460, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Proceed.setFont(font)
        self.Proceed.setObjectName("Proceed")
        self.Proceed.setFont(font)
        self.Patient_name = QtWidgets.QLabel(self.centralwidget)
        self.Patient_name.setGeometry(QtCore.QRect(210, 80, 211, 31))
        self.Patient_name.setText("")
        self.Patient_name.setObjectName("Patient_name")
        self.Patient_UID = QtWidgets.QLabel(self.centralwidget)
        self.Patient_UID.setGeometry(QtCore.QRect(190, 120, 211, 31))
        self.Patient_UID.setText("")
        self.Patient_UID.setObjectName("Patient_UID")
        self.Total_bill = QtWidgets.QLabel(self.centralwidget)
        self.Total_bill.setGeometry(QtCore.QRect(160, 330, 211, 31))
        self.Total_bill.setText("")
        self.Total_bill.setObjectName("Total_bill")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 765, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.windopopulate(pt_UID,totalamount,name)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMRsys"))
        self.label.setText(_translate("MainWindow", "EMRsys"))
        self.label_4.setText(_translate("MainWindow", "Patient Name:"))
        self.label_5.setText(_translate("MainWindow", "patient UID:"))
        self.label_6.setText(_translate("MainWindow", "Total Bill:"))
        self.label_7.setText(_translate("MainWindow", "Amount paid:"))
        self.name.setText(_translate("MainWindow", "Notes:"))
        self.Proceed.setText(_translate("MainWindow", "Proceed"))

    def windopopulate(self,uid,totalbill,name):
        self.label_4.setText("Patient Name:"+str(name[0][0])+" "+str(name[0][1]))
        self.label_5.setText("patient UID:"+str(uid[0][0]))
        self.label_6.setText("Total Bill:"+str(totalbill))

    def feed_the_data(self,uid,billamount,Tx_ID):
        amount_paid = self.Paid_Amount.text()
        status = self.Status.text()
        self.Paid_Amount.clear()
        self.Status.clear()
        val = (uid[0][0],Tx_ID,billamount,amount_paid,status)
        connection.Insert_bill(val)
        valu = (uid[0][0],Tx_ID)
        connection.bill_print_data(uid[0][0])
        connection.bill_print_data1(valu)
        connection.bill_print_data2(valu)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
